name: ChestRefill
version: 1.0
main: me.nikita.chestrefill.ChestRefillPlugin
api-version: 1.21

commands:
  chestrefill:
    description: Main command
    usage: /chestrefill set <x1> <y1> <z1> <x2> <y2> <z2>
    permission: chestrefill.admin

permissions:
  chestrefill.admin:
    default: op